// Code generated by zbridge 0.1.0. DO NOT EDIT.
// Source: src/c_api.zig
// ABI: 8e2d6127f907e51a

//go:build windows && amd64

package zcounter

import _ "embed"

// nativeLib is this platform's shared library, baked into the binary so
// that a program using these bindings has nothing else to install.
//
//go:embed native/windows_x86_64/zcounter.dll
var nativeLib []byte

// nativeName is the file name nativeLib is extracted under.
const nativeName = "zcounter.dll"
