// Code generated by zbridge 0.1.0. DO NOT EDIT.
// Source: src/c_api.zig
// ABI: 8e2d6127f907e51a

//go:build !((linux && amd64) || (linux && arm64) || (darwin && arm64) || (darwin && amd64) || (windows && amd64))

package zcounter

// No native library is embedded for this platform. The symbols still exist
// so the package compiles everywhere, and Load reports a clear error rather
// than the build failing to link. ZCOUNTER_LIB_PATH still works.
var nativeLib []byte

const nativeName = ""
