// Code generated by zbridge 0.1.0. DO NOT EDIT.
// Source: src/c_api.zig
// ABI: 8e2d6127f907e51a

package zcounter

import "github.com/ebitengine/purego"

// One variable per exported Zig function, each holding the raw C-ABI call.
// Nothing here adds behaviour: the widths are the ones the shared library
// actually uses, so a mistake in this file is a miscall, not a type error.

// fnZcounterNew calls zcounter_new() ?*Counter.
var fnZcounterNew func() uintptr

// fnZcounterDestroy calls zcounter_destroy(*Counter) void.
var fnZcounterDestroy func(uintptr)

// fnZcounterAdd calls zcounter_add(i32, i32) i32.
var fnZcounterAdd func(int32, int32) int32

// fnZcounterFeed calls zcounter_feed(*Counter, [*]const u8, usize) u64.
var fnZcounterFeed func(uintptr, *byte, uintptr) uint64

// fnZcounterFeedStr calls zcounter_feed_str(*Counter, [*:0]const u8) u64.
var fnZcounterFeedStr func(uintptr, *byte) uint64

// fnZcounterDigest calls zcounter_digest(*Counter, [*]u8, usize) usize.
var fnZcounterDigest func(uintptr, *byte, uintptr) uintptr

// fnZcounterTotal calls zcounter_total(*Counter, *u64) bool.
var fnZcounterTotal func(uintptr, *uint64) bool

// bind resolves every exported symbol out of an opened library. purego panics
// when a symbol is missing; the loader turns that into an error.
func bind(handle uintptr) {
	purego.RegisterLibFunc(&fnZcounterNew, handle, "zcounter_new")
	purego.RegisterLibFunc(&fnZcounterDestroy, handle, "zcounter_destroy")
	purego.RegisterLibFunc(&fnZcounterAdd, handle, "zcounter_add")
	purego.RegisterLibFunc(&fnZcounterFeed, handle, "zcounter_feed")
	purego.RegisterLibFunc(&fnZcounterFeedStr, handle, "zcounter_feed_str")
	purego.RegisterLibFunc(&fnZcounterDigest, handle, "zcounter_digest")
	purego.RegisterLibFunc(&fnZcounterTotal, handle, "zcounter_total")
}
