// Code generated by zbridge 0.1.0. DO NOT EDIT.
// Source: src/c_api.zig
// ABI: 8e2d6127f907e51a

package zcounter

import (
	"errors"
	"runtime"
	"unsafe"
)

// ErrNullHandle is returned by a constructor when the native library
// produced a null handle. The library itself decides what that means;
// these bindings only refuse to wrap it.
var ErrNullHandle = errors.New("zcounter: null handle")

// emptyScratch backs the pointer passed for an empty slice when the Zig
// parameter is a plain `[*]u8`. Zig's many-item pointer is not optional:
// the callee may assume it is non-null even when the length is 0, so a nil
// pointer there is undefined behaviour rather than an empty buffer. One
// byte of package-level storage gives the callee a real address to hold
// while the length stays honestly 0. Nothing ever reads or writes it.
var emptyScratch [1]byte

// Counter wraps the native `Counter` handle. The zero value is not usable; get one
// from a constructor.
//
// An opaque running counter: an FNV-1a-64 digest over every byte fed to it
// plus the total number of bytes seen. Create one with `zcounter_new` and
// release it with `zcounter_destroy`.
type Counter struct {
	h uintptr
}

// Close releases c by calling zcounter_destroy.
//
// Close is idempotent: a second call is a no-op. It is not safe to call it
// concurrently with the other methods.
func (c *Counter) Close() error {
	if c == nil || c.h == 0 {
		return nil
	}
	handle := c.h
	c.h = 0
	runtime.SetFinalizer(c, nil)
	fnZcounterDestroy(handle)
	return nil
}

// New wraps the exported Zig function zcounter_new.
//
// Allocate a counter from the fixed pool.
//
// Returns null when all 64 slots are in use; the generated bindings turn that
// into an error (Go) or an exception (Python). The returned handle must be
// released exactly once with `zcounter_destroy`.
func New() (*Counter, error) {
	mustLoad()
	cRet := fnZcounterNew()
	if cRet == 0 {
		return nil, ErrNullHandle
	}
	wrapped := &Counter{h: cRet}
	runtime.SetFinalizer(wrapped, func(v *Counter) { _ = v.Close() })
	return wrapped, nil
}

// Add wraps the exported Zig function zcounter_add.
//
// Add two integers with wrapping arithmetic, so no input can trap.
func Add(a int32, b int32) int32 {
	mustLoad()
	cRet := fnZcounterAdd(a, b)
	return cRet
}

// Feed wraps the exported Zig function zcounter_feed.
//
// Mix `data[0..len]` into the counter's digest and add `len` to its byte
// total, returning the new total.
//
// `len == 0` is explicitly allowed and leaves the counter untouched: the
// pointer is never dereferenced in that case, because a zero-length slice in
// Go or an empty `bytes()` in Python can carry a null or dangling data
// pointer. Returns 0 if the handle is not live.
func (c *Counter) Feed(data []byte) uint64 {
	mustLoad()
	if c == nil || c.h == 0 {
		panic("zcounter: Counter used after Close")
	}
	dataPtr := &emptyScratch[0]
	if len(data) > 0 {
		dataPtr = unsafe.SliceData(data)
	}
	cRet := fnZcounterFeed(c.h, dataPtr, uintptr(len(data)))
	runtime.KeepAlive(c)
	runtime.KeepAlive(data)
	return cRet
}

// FeedStr wraps the exported Zig function zcounter_feed_str.
//
// Same as `zcounter_feed`, but over a NUL-terminated string; the terminator
// itself is not counted. Returns the new total, or 0 if the handle is not
// live. A null pointer is treated as an empty string.
func (c *Counter) FeedStr(text string) uint64 {
	mustLoad()
	if c == nil || c.h == 0 {
		panic("zcounter: Counter used after Close")
	}
	textBytes := append([]byte(text), 0)
	cRet := fnZcounterFeedStr(c.h, unsafe.SliceData(textBytes))
	runtime.KeepAlive(c)
	runtime.KeepAlive(textBytes)
	return cRet
}

// Digest wraps the exported Zig function zcounter_digest.
//
// Write the counter's 8-byte big-endian FNV-1a-64 digest into `out[0..out_len]`
// and return the number of bytes **actually written**.
//
// The digest is always 8 bytes, so:
//
//   - `out_len >= 8` writes 8 bytes and returns 8;
//   - `out_len < 8` writes the first `out_len` bytes and returns `out_len`
//     (the digest is truncated, never padded, and `out` is never overrun);
//   - `out_len == 0` writes nothing and returns 0.
//
// Returns 0 if the handle is not live.
func (c *Counter) Digest(out []byte) uintptr {
	mustLoad()
	if c == nil || c.h == 0 {
		panic("zcounter: Counter used after Close")
	}
	outPtr := &emptyScratch[0]
	if len(out) > 0 {
		outPtr = unsafe.SliceData(out)
	}
	cRet := fnZcounterDigest(c.h, outPtr, uintptr(len(out)))
	runtime.KeepAlive(c)
	runtime.KeepAlive(out)
	return cRet
}

// Total wraps the exported Zig function zcounter_total.
//
// Write the counter's running byte total through `out` and return true.
//
// Returns false without touching `out` when the handle is not live, which is
// the out-parameter shape the generators lower into an extra return value.
func (c *Counter) Total() (bool, uint64) {
	mustLoad()
	if c == nil || c.h == 0 {
		panic("zcounter: Counter used after Close")
	}
	var outOut uint64
	cRet := fnZcounterTotal(c.h, &outOut)
	runtime.KeepAlive(c)
	return cRet, outOut
}
