// Code generated by zbridge 0.1.0. DO NOT EDIT.
// Source: src/c_api.zig
// ABI: 8e2d6127f907e51a

#ifndef ZBRIDGE_ZCOUNTER_H
#define ZBRIDGE_ZCOUNTER_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// An opaque running counter: an FNV-1a-64 digest over every byte fed to it
// plus the total number of bytes seen. Create one with `zcounter_new` and
// release it with `zcounter_destroy`.
typedef struct Counter Counter;

// Identifies the exported surface this binary was built from.
uint64_t zcounter_zbridge_abi_hash(void);

// Allocate a counter from the fixed pool.
//
// Returns null when all 64 slots are in use; the generated bindings turn that
// into an error (Go) or an exception (Python). The returned handle must be
// released exactly once with `zcounter_destroy`.
Counter* zcounter_new(void);

// Release a counter back to the pool.
//
// Calling this once per handle is required; calling it again with the same
// (now stale) handle is a no-op rather than a double free, which is what makes
// an idempotent `Close()` / `close()` safe to generate.
void zcounter_destroy(Counter* c);

// Add two integers with wrapping arithmetic, so no input can trap.
int32_t zcounter_add(int32_t a, int32_t b);

// Mix `data[0..len]` into the counter's digest and add `len` to its byte
// total, returning the new total.
//
// `len == 0` is explicitly allowed and leaves the counter untouched: the
// pointer is never dereferenced in that case, because a zero-length slice in
// Go or an empty `bytes()` in Python can carry a null or dangling data
// pointer. Returns 0 if the handle is not live.
uint64_t zcounter_feed(Counter* c, const uint8_t* data, size_t len);

// Same as `zcounter_feed`, but over a NUL-terminated string; the terminator
// itself is not counted. Returns the new total, or 0 if the handle is not
// live. A null pointer is treated as an empty string.
uint64_t zcounter_feed_str(Counter* c, const char* text);

// Write the counter's 8-byte big-endian FNV-1a-64 digest into `out[0..out_len]`
// and return the number of bytes **actually written**.
//
// The digest is always 8 bytes, so:
//
//   * `out_len >= 8` writes 8 bytes and returns 8;
//   * `out_len < 8` writes the first `out_len` bytes and returns `out_len`
//     (the digest is truncated, never padded, and `out` is never overrun);
//   * `out_len == 0` writes nothing and returns 0.
//
// Returns 0 if the handle is not live.
size_t zcounter_digest(Counter* c, uint8_t* out, size_t out_len);

// Write the counter's running byte total through `out` and return true.
//
// Returns false without touching `out` when the handle is not live, which is
// the out-parameter shape the generators lower into an extra return value.
bool zcounter_total(Counter* c, uint64_t* out);

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // ZBRIDGE_ZCOUNTER_H
