# Code generated by zbridge 0.1.0. DO NOT EDIT.
# Source: src/c_api.zig
# ABI: 8e2d6127f907e51a

"""ctypes prototypes for every exported function.

One block per `export fn`, setting argtypes and restype and nothing
else. Call the idiomatic layer in _gen.py instead of this module.
"""

from __future__ import annotations

import ctypes
import threading

from ._loader_gen import get_lib

_ffi: ctypes.CDLL | None = None
_ffi_lock = threading.Lock()


def get_ffi() -> ctypes.CDLL:
    """Return the library with every prototype declared on it.

    Bound once, under a lock: an unguarded check-then-set lets two threads
    each load the library and each run bind() over it, and on a
    free-threaded build there is no GIL making those steps look atomic.
    """
    global _ffi
    ffi = _ffi
    if ffi is not None:
        return ffi
    with _ffi_lock:
        if _ffi is None:
            lib = get_lib()
            bind(lib)
            _ffi = lib
        return _ffi


def bind(lib: ctypes.CDLL) -> None:
    """Declare argtypes/restype for every export. Idempotent."""

    # zcounter_new() ?*Counter
    _fn = lib.zcounter_new
    _fn.argtypes = []
    # Must be explicit: the ctypes default of c_int would truncate this pointer.
    _fn.restype = ctypes.c_void_p

    # zcounter_destroy(*Counter) void
    _fn = lib.zcounter_destroy
    _fn.argtypes = [ctypes.c_void_p]
    _fn.restype = None

    # zcounter_add(i32, i32) i32
    _fn = lib.zcounter_add
    _fn.argtypes = [ctypes.c_int32, ctypes.c_int32]
    _fn.restype = ctypes.c_int32

    # zcounter_feed(*Counter, [*]const u8, usize) u64
    _fn = lib.zcounter_feed
    _fn.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_size_t]
    _fn.restype = ctypes.c_uint64

    # zcounter_feed_str(*Counter, [*:0]const u8) u64
    _fn = lib.zcounter_feed_str
    _fn.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
    _fn.restype = ctypes.c_uint64

    # zcounter_digest(*Counter, [*]u8, usize) usize
    _fn = lib.zcounter_digest
    _fn.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_char), ctypes.c_size_t]
    _fn.restype = ctypes.c_size_t

    # zcounter_total(*Counter, *u64) bool
    _fn = lib.zcounter_total
    _fn.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_uint64)]
    _fn.restype = ctypes.c_bool
