# Code generated by zbridge 0.1.0. DO NOT EDIT.
# Source: src/c_api.zig
# ABI: 8e2d6127f907e51a

"""The zcounter API: one class per handle, one function per export.

Regenerated in full on every zbridge run. Put your own code in
__init__.py, or subclass from there; edits here are lost.
"""

from __future__ import annotations

import ctypes
import threading

from ._ffi_gen import get_ffi

__all__ = [
    "ZcounterError",
    "Counter",
    "add",
]


class ZcounterError(RuntimeError):
    """Raised when a zcounter call fails or returns a NULL handle."""


#: One byte this module owns, handed to the callee in place of an empty
#: buffer's pointer. Zig spells a non-optional buffer parameter `[*]u8`,
#: which is a non-null pointer type: passing NULL is undefined behaviour
#: even when the paired length is 0. What CPython hands out for a
#: zero-length buffer is an implementation detail, so it is not relied on.
_EMPTY = (ctypes.c_char * 1)()


def _bytes_in(
    data: bytes | bytearray | memoryview | None,
    *,
    nonnull: bool = True,
) -> tuple[object, int]:
    """Borrow a read-only pointer to `data`, copying only when forced to.

    `bytes` is passed straight through (ctypes converts it to a char* with
    no copy). A `bytearray` or writable `memoryview` is wrapped in place, so
    the callee reads the caller's own memory. A read-only `memoryview` over
    a non-`bytes` object is the one case that has to be copied.

    `nonnull` is True for a `[*]const u8` parameter and False for the
    optional `?[*]const u8`, which is the only shape where the callee
    asked to be able to see NULL; there, and only there, `None` is
    accepted and passed through as NULL.
    """
    if data is None:
        if nonnull:
            raise TypeError("this buffer argument is not optional, so None is not allowed")
        return None, 0
    if isinstance(data, bytes):
        if nonnull and not data:
            return _EMPTY, 0
        return data, len(data)
    view = memoryview(data)
    if view.ndim != 1 or view.format != "B":
        view = view.cast("B")
    if nonnull and view.nbytes == 0:
        return _EMPTY, 0
    if view.readonly:
        raw = view.tobytes()
        return raw, len(raw)
    return (ctypes.c_char * view.nbytes).from_buffer(view), view.nbytes


def _bytes_out(buf: bytearray | None, *, nonnull: bool = True) -> tuple[object, int]:
    """Wrap a caller-allocated buffer so the callee can write into it.

    The result aliases `buf`; nothing is copied back afterwards, which is
    why a read-only object is rejected here instead of silently discarding
    whatever the callee wrote.

    An empty buffer still yields a real address when `nonnull` is set, for
    the same reason as in _bytes_in; the length stays 0, so a correct
    callee never dereferences it. `None` is accepted only for the optional
    `?[*]u8`, where it becomes NULL.
    """
    if buf is None:
        if nonnull:
            raise TypeError("this buffer argument is not optional, so None is not allowed")
        return None, 0
    view = memoryview(buf)
    if view.readonly:
        raise TypeError(
            "expected a writable buffer such as bytearray, got a read-only "
            f"{type(buf).__name__}"
        )
    if view.ndim != 1 or view.format != "B":
        view = view.cast("B")
    if nonnull and view.nbytes == 0:
        return _EMPTY, 0
    return (ctypes.c_char * view.nbytes).from_buffer(view), view.nbytes


def _cstr_in(text: str | bytes) -> bytes:
    """Encode a NUL-terminated string argument. ctypes appends the NUL."""
    if isinstance(text, bytes):
        return text
    return text.encode("utf-8")


class Counter:
    """An opaque running counter: an FNV-1a-64 digest over every byte fed to it
    plus the total number of bytes seen. Create one with `zcounter_new` and
    release it with `zcounter_destroy`.
    """

    __slots__ = ("_handle", "_owned", "_lock")

    def __init__(self, handle: int, owned: bool = True) -> None:
        """Wrap a raw pointer. Prefer the constructors below.

        `owned` decides what close() and __del__ do: an owning wrapper calls
        the native destructor, a borrowed one only drops its reference. Only
        a constructor can know the answer, so only a constructor owns.
        """
        self._handle: ctypes.c_void_p | None = None
        self._owned: bool = owned
        self._lock = threading.Lock()
        if not handle:
            raise ZcounterError("Counter: NULL handle")
        self._handle = ctypes.c_void_p(handle)

    @classmethod
    def _borrow(cls, handle: int) -> Counter:
        """Wrap a pointer this object does not own; close() will not free it."""
        return cls(handle, owned=False)

    def _as_arg(self) -> ctypes.c_void_p:
        """Return the pointer, refusing to use one that was closed."""
        if self._handle is None:
            raise ZcounterError("Counter is closed")
        return self._handle

    @classmethod
    def new(cls) -> Counter:
        """Allocate a counter from the fixed pool.

        Returns null when all 64 slots are in use; the generated bindings turn that
        into an error (Go) or an exception (Python). The returned handle must be
        released exactly once with `zcounter_destroy`.
        """
        _lib = get_ffi()
        _ret = _lib.zcounter_new()
        if not _ret:
            raise ZcounterError("zcounter_new returned NULL")
        return cls(_ret)

    def feed(self, data: bytes | bytearray | memoryview) -> int:
        """Mix `data[0..len]` into the counter's digest and add `len` to its byte
        total, returning the new total.

        `len == 0` is explicitly allowed and leaves the counter untouched: the
        pointer is never dereferenced in that case, because a zero-length slice in
        Go or an empty `bytes()` in Python can carry a null or dangling data
        pointer. Returns 0 if the handle is not live.
        """
        _lib = get_ffi()
        _data_ptr, _data_len = _bytes_in(data)
        _ret = _lib.zcounter_feed(self._as_arg(), _data_ptr, _data_len)
        return _ret

    def feed_str(self, text: str | bytes) -> int:
        """Same as `zcounter_feed`, but over a NUL-terminated string; the terminator
        itself is not counted. Returns the new total, or 0 if the handle is not
        live. A null pointer is treated as an empty string.
        """
        _lib = get_ffi()
        _text_c = _cstr_in(text)
        _ret = _lib.zcounter_feed_str(self._as_arg(), _text_c)
        return _ret

    def digest(self, out: bytearray) -> int:
        """Write the counter's 8-byte big-endian FNV-1a-64 digest into `out[0..out_len]`
        and return the number of bytes **actually written**.

        The digest is always 8 bytes, so:

          * `out_len >= 8` writes 8 bytes and returns 8;
          * `out_len < 8` writes the first `out_len` bytes and returns `out_len`
            (the digest is truncated, never padded, and `out` is never overrun);
          * `out_len == 0` writes nothing and returns 0.

        Returns 0 if the handle is not live.
        """
        _lib = get_ffi()
        _out_ptr, _out_len = _bytes_out(out)
        _ret = _lib.zcounter_digest(self._as_arg(), _out_ptr, _out_len)
        return _ret

    def total(self) -> tuple[bool, int]:
        """Write the counter's running byte total through `out` and return true.

        Returns false without touching `out` when the handle is not live, which is
        the out-parameter shape the generators lower into an extra return value.
        """
        _lib = get_ffi()
        _out_out = ctypes.c_uint64()
        _ret = _lib.zcounter_total(self._as_arg(), ctypes.byref(_out_out))
        return _ret, _out_out.value

    def close(self) -> None:
        """Release the handle by calling ``zcounter_destroy``.

        Idempotent and thread safe: the handle is taken under a per-instance
        lock and cleared before the destructor runs, so a second call, a call
        after __exit__, and a __del__ racing another thread all do nothing.

        A wrapper that does not own its handle (see _borrow) only drops it:
        the native destructor is never called on a borrowed pointer.
        """
        with self._lock:
            handle, self._handle = self._handle, None
            owned = self._owned
        if handle is None or not owned or get_ffi is None:
            # get_ffi can already be None during interpreter shutdown.
            return
        get_ffi().zcounter_destroy(handle)

    def __enter__(self) -> Counter:
        return self

    def __exit__(self, exc_type: object, exc: object, tb: object) -> None:
        self.close()

    def __del__(self) -> None:
        # A safety net, not the intended path: use `with` or close().
        # Anything can already be torn down here, so nothing may escape.
        try:
            self.close()
        except Exception:
            pass

    def __repr__(self) -> str:
        if self._handle is None:
            return "<Counter closed>"
        return f"<Counter open{'' if self._owned else ', borrowed'}>"


def add(a: int, b: int) -> int:
    """Add two integers with wrapping arithmetic, so no input can trap."""
    _lib = get_ffi()
    _ret = _lib.zcounter_add(a, b)
    return _ret
