//! The pipeline: source -> parse -> validate -> generate -> a list of files.
//! No CLI and no build-system concerns live here; both front ends call `run`
//! and then `writeFiles`, which is what makes their output identical.

const std = @import("std");
const Io = std.Io;

const ir = @import("ir.zig");
const diag = @import("diagnostics.zig");
const targets = @import("targets.zig");
const abi_hash = @import("abi_hash.zig");
const parse = @import("parse.zig");
const validate = @import("validate.zig");
const gen = @import("../gen/context.zig");
const go_gen = @import("../gen/go.zig");
const python_gen = @import("../gen/python.zig");
const c_gen = @import("../gen/c_header.zig");
const version = @import("../version.zig");

pub const Options = struct {
    /// Library base name, e.g. "zpdf". Derived from the input file name when
    /// the front end doesn't supply one.
    lib_name: []const u8,
    input_path: []const u8,
    targets: []const targets.Target = targets.default,
    link_libc: bool = false,
    emit_go: bool = true,
    emit_python: bool = true,
    emit_c_header: bool = false,
    go: gen.GoOptions = .{},
    python: gen.PythonOptions = .{},
};

pub const Result = struct {
    api: ir.Api,
    abi_hash: u64,
    abi_hash_hex: []const u8,
    files: []const gen.OutFile,
};

/// Returns null when parsing or validation produced errors; `diags` then holds
/// every problem found, not just the first.
pub fn run(
    arena: std.mem.Allocator,
    source: [:0]const u8,
    opts: Options,
    diags: *diag.List,
) !?Result {
    const api = try parse.parseSource(arena, opts.lib_name, source, diags) orelse {
        // A failed parse renders its diagnostics too, so it gets the same
        // stable ordering the validation path gets.
        diags.sort();
        return null;
    };
    try validate.validate(arena, api, diags);
    diags.sort();
    if (diags.hasErrors()) return null;

    const hash = abi_hash.compute(api);
    const hash_hex = try abi_hash.format(arena, hash);

    const ctx: gen.Context = .{
        .api = &api,
        .abi_hash = hash,
        .abi_hash_hex = hash_hex,
        .targets = opts.targets,
        .link_libc = opts.link_libc,
        .version = version.string,
        .input_path = opts.input_path,
        .go = opts.go,
        .python = opts.python,
    };

    var files: gen.FileList = .empty;
    try emitZigGlue(arena, ctx, &files);
    if (opts.emit_go) try go_gen.generate(arena, ctx, &files);
    if (opts.emit_python) try python_gen.generate(arena, ctx, &files);
    if (opts.emit_c_header) try c_gen.generate(arena, ctx, &files);

    return .{
        .api = api,
        .abi_hash = hash,
        .abi_hash_hex = hash_hex,
        .files = try files.toOwnedSlice(arena),
    };
}

/// The library root the build step compiles: it pulls in the user's file and
/// adds one export so the loader can check the ABI at load time.
fn emitZigGlue(arena: std.mem.Allocator, ctx: gen.Context, files: *gen.FileList) !void {
    const bytes = try std.fmt.allocPrint(arena,
        \\// Code generated by zbridge {s}. DO NOT EDIT.
        \\//
        \\// Compiled as the shared library's root module. `zbridge_input` is the
        \\// user's own file; referencing it here is what causes its `export fn`
        \\// declarations to be analyzed and emitted.
        \\const input = @import("zbridge_input");
        \\
        \\comptime {{
        \\    _ = input;
        \\}}
        \\
        \\/// Identifies the exported surface this binary was built from. The
        \\/// generated bindings carry the same constant and refuse to run against
        \\/// a binary that reports a different one.
        \\export fn {s}_zbridge_abi_hash() u64 {{
        \\    return 0x{s};
        \\}}
        \\
    , .{ ctx.version, ctx.libName(), ctx.abi_hash_hex });

    try files.append(arena, .{
        .lang = .zig_glue,
        .path = try std.fmt.allocPrint(arena, "{s}_zbridge_root.zig", .{ctx.libName()}),
        .bytes = bytes,
    });
}

// ---------------------------------------------------------------------------
// Writing the result to disk
// ---------------------------------------------------------------------------

pub const Roots = struct {
    go: ?[]const u8 = null,
    python: ?[]const u8 = null,
    c: ?[]const u8 = null,
    zig_glue: ?[]const u8 = null,

    pub fn forLang(self: Roots, lang: gen.Lang) ?[]const u8 {
        return switch (lang) {
            .go => self.go,
            .python => self.python,
            .c => self.c,
            .zig_glue => self.zig_glue,
        };
    }
};

pub const Action = enum { created, overwritten, unchanged, skipped_exists };

pub const FileAction = struct {
    path: []const u8,
    action: Action,
};

pub const WriteStats = struct {
    actions: []const FileAction,

    pub fn count(self: WriteStats, a: Action) usize {
        var n: usize = 0;
        for (self.actions) |x| {
            if (x.action == a) n += 1;
        }
        return n;
    }
};

pub const WriteOptions = struct {
    /// Overwrite user_scaffold files too.
    force: bool = false,
    /// Compute actions without touching the filesystem.
    dry_run: bool = false,
};

/// Write every file, returning what happened to each. The whole list is only
/// available when the run succeeds; `writeFilesInto` is the form to use when a
/// partial failure still has to be reported.
pub fn writeFiles(
    io: Io,
    arena: std.mem.Allocator,
    roots: Roots,
    files: []const gen.OutFile,
    opts: WriteOptions,
) ![]const FileAction {
    var actions: std.ArrayList(FileAction) = .empty;
    try writeFilesInto(io, arena, roots, files, opts, &actions);
    return actions.toOwnedSlice(arena);
}

/// Same, but appends each action to `actions` as it happens, so a failure
/// part-way through (ENOSPC, a read-only directory) still leaves the caller
/// holding the list of files that were already written. Nothing is appended
/// for a file whose write failed: the list is what is on disk, not what was
/// attempted.
pub fn writeFilesInto(
    io: Io,
    arena: std.mem.Allocator,
    roots: Roots,
    files: []const gen.OutFile,
    opts: WriteOptions,
    actions: *std.ArrayList(FileAction),
) !void {
    const cwd: Io.Dir = .cwd();

    for (files) |f| {
        const root = roots.forLang(f.lang) orelse continue;
        const full = try std.fs.path.join(arena, &.{ root, f.path });

        // "Cannot be read" is not "is not there". Treating the two alike is
        // what would let an unreadable hand-written scaffold — a directory in
        // its place, a dangling symlink, mode 000, a file another process has
        // locked — be reported as `.created` and clobbered. D3 and plan §6
        // rest on that never happening.
        const existing: ?[]u8 = cwd.readFileAlloc(io, full, arena, .limited(64 << 20)) catch |err| switch (err) {
            error.FileNotFound => null,
            else => |unreadable| {
                if (f.tier == .user_scaffold and !opts.force) {
                    // Something is there and it is the user's. Leave it alone
                    // and report it as kept, exactly as an existing scaffold
                    // that was read successfully would be.
                    try actions.append(arena, .{ .path = full, .action = .skipped_exists });
                    continue;
                }
                // A generated file zbridge cannot read is a broken tree, not a
                // fresh one: fail loudly rather than overwrite whatever is
                // there. `--force` on a scaffold is the one explicit licence
                // to overwrite, and it still fails loudly if the write itself
                // cannot happen.
                if (f.tier != .user_scaffold) return unreadable;
                if (opts.dry_run) {
                    try actions.append(arena, .{ .path = full, .action = .overwritten });
                    continue;
                }
                try writeOne(io, cwd, full, f.bytes);
                try actions.append(arena, .{ .path = full, .action = .overwritten });
                continue;
            },
        };

        const action: Action = blk: {
            if (existing) |old| {
                if (f.tier == .user_scaffold and !opts.force) break :blk .skipped_exists;
                if (std.mem.eql(u8, old, f.bytes)) break :blk .unchanged;
                break :blk .overwritten;
            }
            break :blk .created;
        };

        if (!opts.dry_run and action != .unchanged and action != .skipped_exists) {
            try writeOne(io, cwd, full, f.bytes);
        }
        try actions.append(arena, .{ .path = full, .action = action });
    }
}

fn writeOne(io: Io, cwd: Io.Dir, full: []const u8, bytes: []const u8) !void {
    if (std.fs.path.dirname(full)) |dir| {
        try cwd.createDirPath(io, dir);
    }
    try cwd.writeFile(io, .{ .sub_path = full, .data = bytes });
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const testing = std.testing;

const TestTree = struct {
    tmp: testing.TmpDir,
    root: []const u8,

    fn init(arena: std.mem.Allocator) !TestTree {
        var tmp = testing.tmpDir(.{});
        errdefer tmp.cleanup();
        const root = try std.fs.path.join(arena, &.{ ".zig-cache", "tmp", &tmp.sub_path });
        return .{ .tmp = tmp, .root = root };
    }

    fn deinit(self: *TestTree) void {
        self.tmp.cleanup();
    }

    fn roots(self: TestTree) Roots {
        return .{ .go = self.root };
    }
};

test "an unreadable scaffold is kept, not clobbered" {
    var arena_state: std.heap.ArenaAllocator = .init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const io = testing.io;

    var tree = try TestTree.init(arena);
    defer tree.deinit();

    // A directory where the scaffold would go: readFileAlloc fails with
    // something other than FileNotFound, which the old code read as "absent".
    try tree.tmp.dir.createDirPath(io, "wrapper.go");
    try tree.tmp.dir.writeFile(io, .{ .sub_path = "wrapper.go/keep.txt", .data = "mine\n" });

    const files = [_]gen.OutFile{.{
        .lang = .go,
        .path = "wrapper.go",
        .bytes = "// generated\n",
        .tier = .user_scaffold,
    }};

    const actions = try writeFiles(io, arena, tree.roots(), &files, .{});
    try testing.expectEqual(@as(usize, 1), actions.len);
    try testing.expectEqual(Action.skipped_exists, actions[0].action);

    // The user's tree is untouched.
    const kept = try tree.tmp.dir.readFileAlloc(io, "wrapper.go/keep.txt", arena, .limited(1 << 10));
    try testing.expectEqualStrings("mine\n", kept);
}

test "an unreadable generated file fails loudly instead of being overwritten" {
    var arena_state: std.heap.ArenaAllocator = .init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const io = testing.io;

    var tree = try TestTree.init(arena);
    defer tree.deinit();

    try tree.tmp.dir.createDirPath(io, "blocked_gen.go");

    const files = [_]gen.OutFile{
        .{ .lang = .go, .path = "first_gen.go", .bytes = "// one\n" },
        .{ .lang = .go, .path = "blocked_gen.go", .bytes = "// two\n" },
        .{ .lang = .go, .path = "third_gen.go", .bytes = "// three\n" },
    };

    // The caller-owned list survives the error: what reached disk is reportable.
    var actions: std.ArrayList(FileAction) = .empty;
    try testing.expectError(
        error.IsDir,
        writeFilesInto(io, arena, tree.roots(), &files, .{}, &actions),
    );
    try testing.expectEqual(@as(usize, 1), actions.items.len);
    try testing.expectEqualStrings("first_gen.go", std.fs.path.basename(actions.items[0].path));
    try testing.expectEqual(Action.created, actions.items[0].action);

    // The third file was never reached, so it is not on disk either.
    try testing.expectError(
        error.FileNotFound,
        tree.tmp.dir.readFileAlloc(io, "third_gen.go", arena, .limited(1 << 10)),
    );
}

test "writeFiles creates, leaves unchanged, overwrites and keeps a scaffold" {
    var arena_state: std.heap.ArenaAllocator = .init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const io = testing.io;

    var tree = try TestTree.init(arena);
    defer tree.deinit();

    const files = [_]gen.OutFile{
        .{ .lang = .go, .path = "lib_ffi_gen.go", .bytes = "// v1\n" },
        .{ .lang = .go, .path = "wrapper.go", .bytes = "// scaffold\n", .tier = .user_scaffold },
    };

    const first = try writeFiles(io, arena, tree.roots(), &files, .{});
    try testing.expectEqual(Action.created, first[0].action);
    try testing.expectEqual(Action.created, first[1].action);

    const again = try writeFiles(io, arena, tree.roots(), &files, .{});
    try testing.expectEqual(Action.unchanged, again[0].action);
    try testing.expectEqual(Action.skipped_exists, again[1].action);

    const changed = [_]gen.OutFile{
        .{ .lang = .go, .path = "lib_ffi_gen.go", .bytes = "// v2\n" },
        .{ .lang = .go, .path = "wrapper.go", .bytes = "// regenerated\n", .tier = .user_scaffold },
    };
    const third = try writeFiles(io, arena, tree.roots(), &changed, .{});
    try testing.expectEqual(Action.overwritten, third[0].action);
    try testing.expectEqual(Action.skipped_exists, third[1].action);

    const scaffold = try tree.tmp.dir.readFileAlloc(io, "wrapper.go", arena, .limited(1 << 10));
    try testing.expectEqualStrings("// scaffold\n", scaffold);

    const forced = try writeFiles(io, arena, tree.roots(), &changed, .{ .force = true });
    try testing.expectEqual(Action.overwritten, forced[1].action);
    const rewritten = try tree.tmp.dir.readFileAlloc(io, "wrapper.go", arena, .limited(1 << 10));
    try testing.expectEqualStrings("// regenerated\n", rewritten);
}

test "a dry run reports without touching the filesystem" {
    var arena_state: std.heap.ArenaAllocator = .init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const io = testing.io;

    var tree = try TestTree.init(arena);
    defer tree.deinit();

    const files = [_]gen.OutFile{.{ .lang = .go, .path = "lib_ffi_gen.go", .bytes = "// v1\n" }};
    const actions = try writeFiles(io, arena, tree.roots(), &files, .{ .dry_run = true });
    try testing.expectEqual(Action.created, actions[0].action);
    try testing.expectError(
        error.FileNotFound,
        tree.tmp.dir.readFileAlloc(io, "lib_ffi_gen.go", arena, .limited(1 << 10)),
    );
}
